### ISSUE TITLE
Can't compare file against streamed HTTP GET

### ISSUE THREAD

**Issue by michael-ts** [fent/node-stream-equal#6]
I'm trying to compare the results of an HTTP GET (as issued by the "request" library) to a file on disk:

```
var rs1 = fs.createReadStream(filepath)
var rs2 = request.get(URL,{encoding:null})

streamEqual(rs1,rs2,function(err,equal) {
	if (err) throw err
	console.log(equal)
})

```

However, the two are never reported as equal, even though they should be.  If I modify this slightly to pipe the output of the request to a new file using the code below, the two files compare exactly (using `cmp file file.GOT`):

```
var ws2 = fs.createWriteStream(filepath+".GOT")
rs2.pipe(ws2)
```

I have tried the above code both before and after the call to streamEqual, and it always winds up creating a file identical to the original.

I put a few console logging statement in stream-equal/lib/index.js and it reports that the compare is failing because one stream is ending before the other.   Specifically, line 145-150 I modified as follows:

```
if (newPos > otherStream.pos) {
      if (otherStream.ended) {
        // If this stream is still emitting `data` events but the other has
        // ended, then this is longer than the other one.
       console.log("compare failed due to stream ending:",stream.id,",",newPos,",",otherStream.pos)
        return callback(null, false);
      }
```

The values output were stream.id=1, newPos=131072, otherStream.pos=0.  I tried reversing the order of the parameters rs1 and rs2 to streamEqual() and got stream.id=2, newPos=65536, otherStream.pos=0.

IF I attach to the file's data event:

```
rs1.on('data',function() {
  // not even doing anything here!
})
```

Then inexplicably streamEqual starts returning true to the callback!  Unfortunately, it also returns true even if I request the wrong file and would expect the compare to fail!

Might this be related to the fact that stream-equal is over-riding the stream's read function?

**Comment by fent** [comment]
This is due to the request module not returning a Readable stream, but its own stream type, which can only be piped. Usually, that's how streams are consumed, but not in this module.

It was removed in https://github.com/fent/node-stream-equal/commit/6c2022c0b62a3bb77e81ef1aff956aa2c07ae93d, I'll add it back since the request module is widely used. And there might be more modules that imitate readable streams similarly.

The stream's read function isn't being overwritten, the variables `stream1` and `stream2` refer to the state objects defined above. Would be a good idea if I were to give them a better name.
