### ISSUE TITLE
Please change "@types/node": "*" to a dev dependency

### ISSUE THREAD

**Issue by lukiano** [fent/node-stream-equal#8]
https://github.com/fent/node-stream-equal/blob/master/package.json#L27
Since it conflicts with other existing node typings

**Comment by fent** [comment]
Hi, this change came a [PR](https://github.com/fent/node-stream-equal/pull/7) a few days ago. I don't use Typescript myself regularly, I'm not too familiar with adding typings to libraries yet so it's possible I made a mistake.

Thoughts @ethanresnick ?

**Comment by ethanresnick** [comment]
@lukiano Can you describe the conflict you're seeing in more detail? If you already have node typings installed from another module, I'm pretty sure npm shouldn't install anything.

As far as putting it in devDependencies: the typescript docs [are pretty clear](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies) that dependencies is the right place for it, unless I'm misunderstanding something.

**Comment by lukiano** [comment]
I don't think that doc applies to the standard Node.JS type definitions, but anyway, the conflict I have is that I'm using another type definition for node and it isn't exactly the same as the one in @types/node, so the IDE messes up. I'll try to update my work to typescript 2 to use that one. If no one else is complaining about this, then I guess you can choose not to do it.

**Comment by ethanresnick** [comment]
> I'll try to update my work to typescript 2 to use that one.

I don't fully understand the changes to the type declaration format in typescript 2.0, but it sounds like that's the problem here. The whole `@types` infrastructure is built for 2.0, so I think the best way not to have problems pre TS2 is to avoid `@types` entirely, and continue to use the TS1 type declaration infrastructure (typings/tsd). Would it work for you to just have your IDE/TS compiler totally ignore the `node_modules/@types` folder? (If you're trying to get some type declarations from `@types` for convenience, but then ignore others because they don't work with TS <2, I think that's a non-standard enough workflow that it'll be tricky.)

> If no one else is complaining about this, then I guess you can choose not to do it.

I obviously don't have the final say, but I would like to figure out how to make it work for you. I just don't want to break it for others in the process.

**Comment by lukiano** [comment]
I updated my project to TS2 (luckily was quite easy) and there are no issues now.

**Comment by BTMPL** [comment]
Hello; are there plans to move with this issue? We're runing behind a proxy with Artifactory in the middle, and it's not possible to install scoped packages with our current setup. I believe that for node packages typing should be moved to devDependencies, as they are not used in normal workflow when consuming the library.

**Comment by fent** [comment]
`devDependencies` are meant for dependencies that are used for developing the module itself, such as tests, and not just using the module as a dependency. Not sure what the solution for this is, maybe looking at your setup and seeing why scoped packages can't be installed.

We could also list the dependency in [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) instead. Since it the module installation will continue if the dependency fails to install.

**Comment by BTMPL** [comment]
I agree - using optionalDependencies sounds like a good idea that would satisfy both users that are consuming this package as part of their dependency chain (in which case they probably will not need the typing support) and those who wish to use it as a direct dependency.

**Comment by ethanresnick** [comment]
Yup, 👍 to `optionalDependencies`; that sounds like a win-win solution
